// benchmarks/cross-library/solid/template.tsx
/** @jsxRuntime automatic */
/** @jsxImportSource solid-js */
import {
  Body,
  Button,
  Column,
  Container,
  Head,
  Heading,
  Hr,
  Html,
  Img,
  Link,
  Preview,
  Row,
  Section,
  Text,
} from '@akin01/solid-email';
import type { JSX } from 'solid-js';
import { For } from 'solid-js';
import {
  features,
  footerLinks,
  marketingProps,
  products,
  updates,
} from '../shared/fixture-data';

export type SolidMarketingEmailProps = {
  preview?: string;
  headline?: JSX.Element;
  intro?: JSX.Element;
  ctaHref?: string;
  footerReason?: JSX.Element;
};

export function SolidMarketingEmail(props: SolidMarketingEmailProps = {}) {
  const data = { ...marketingProps, ...props };
  return (
    <Html lang="en">
      <Head />
      <Preview>{data.preview}</Preview>
      <Body style={styles.body}>
        <Container style={styles.container}>
          <Section style={styles.hero}>
            <Heading as="h1" style={styles.heading}>
              {data.headline}
            </Heading>
            <Text style={styles.intro}>{data.intro}</Text>
            <Button href={data.ctaHref} style={styles.button}>
              View the launch notes
            </Button>
          </Section>

          <Hr style={styles.rule} />

          <Section>
            <Heading as="h2" style={styles.sectionHeading}>
              What this fixture covers
            </Heading>
            <For each={features}>
              {(feature) => (
                <Section style={styles.card}>
                  <Heading as="h3" style={styles.cardTitle}>
                    {feature.title}
                  </Heading>
                  <Text style={styles.copy}>{feature.body}</Text>
                </Section>
              )}
            </For>
          </Section>

          <Section style={styles.productSection}>
            <Heading as="h2" style={styles.sectionHeading}>
              Product highlights
            </Heading>
            <Row>
              <For each={products}>
                {(product) => (
                  <Column style={styles.productColumn}>
                    <Img
                      alt={`${product.title} icon`}
                      height="72"
                      src={product.image}
                      style={styles.productImage}
                      width="72"
                    />
                    <Text style={styles.productTitle}>{product.title}</Text>
                    <Text style={styles.productPrice}>{product.price}</Text>
                  </Column>
                )}
              </For>
            </Row>
          </Section>

          <Section>
            <Heading as="h2" style={styles.sectionHeading}>
              Release notes
            </Heading>
            <For each={updates}>
              {(update) => (
                <Row>
                  <Column style={styles.updateIndexColumn}>
                    <Text style={styles.updateIndex}>
                      {update.title.split(' ')[2]}
                    </Text>
                  </Column>
                  <Column>
                    <Text style={styles.updateTitle}>{update.title}</Text>
                    <Text style={styles.copy}>{update.body}</Text>
                  </Column>
                </Row>
              )}
            </For>
          </Section>

          <Hr style={styles.rule} />

          <Section style={styles.footer}>
            <Text style={styles.footerText}>{data.footerReason}</Text>
            <Text style={styles.footerText}>
              <For each={footerLinks}>
                {([label, href], index) => (
                  <span>
                    {index() > 0 ? ' · ' : ''}
                    <Link href={href} style={styles.footerLink}>
                      {label}
                    </Link>
                  </span>
                )}
              </For>
            </Text>
          </Section>
        </Container>
      </Body>
    </Html>
  );
}

export const createSolidMarketingEmail = (props?: SolidMarketingEmailProps) => (
  <SolidMarketingEmail {...props} />
);

const styles = {
  body: {
    backgroundColor: '#f6f9fc',
    color: '#1f2937',
    fontFamily:
      '-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Ubuntu,sans-serif',
    margin: 0,
  },
  container: {
    backgroundColor: '#ffffff',
    border: '1px solid #e5e7eb',
    borderRadius: '16px',
    margin: '32px auto',
    padding: '32px',
    width: '640px',
  },
  hero: {
    backgroundColor: '#111827',
    borderRadius: '14px',
    color: '#ffffff',
    padding: '32px',
  },
  heading: {
    color: '#ffffff',
    fontSize: '32px',
    lineHeight: '40px',
    margin: '0 0 16px',
  },
  intro: {
    color: '#d1d5db',
    fontSize: '16px',
    lineHeight: '26px',
    margin: '0 0 24px',
  },
  button: {
    backgroundColor: '#7c3aed',
    borderRadius: '8px',
    color: '#ffffff',
    fontSize: '15px',
    fontWeight: 700,
    padding: '14px 22px',
  },
  rule: {
    borderColor: '#e5e7eb',
    margin: '28px 0',
  },
  sectionHeading: {
    color: '#111827',
    fontSize: '22px',
    lineHeight: '30px',
    margin: '0 0 16px',
  },
  card: {
    backgroundColor: '#f9fafb',
    border: '1px solid #e5e7eb',
    borderRadius: '12px',
    marginBottom: '12px',
    padding: '16px',
  },
  cardTitle: {
    color: '#111827',
    fontSize: '16px',
    lineHeight: '24px',
    margin: '0 0 6px',
  },
  copy: {
    color: '#4b5563',
    fontSize: '14px',
    lineHeight: '22px',
    margin: '0 0 12px',
  },
  productSection: {
    padding: '8px 0',
  },
  productColumn: {
    padding: '12px',
    width: '33.333%',
  },
  productImage: {
    borderRadius: '14px',
    display: 'block',
    margin: '0 auto 10px',
  },
  productTitle: {
    color: '#111827',
    fontSize: '14px',
    fontWeight: 700,
    lineHeight: '20px',
    margin: '0',
    textAlign: 'center',
  },
  productPrice: {
    color: '#7c3aed',
    fontSize: '13px',
    fontWeight: 700,
    lineHeight: '18px',
    margin: '4px 0 0',
    textAlign: 'center',
  },
  updateIndexColumn: {
    width: '44px',
  },
  updateIndex: {
    backgroundColor: '#ede9fe',
    borderRadius: '999px',
    color: '#6d28d9',
    fontSize: '12px',
    fontWeight: 700,
    lineHeight: '28px',
    margin: '0',
    textAlign: 'center',
    width: '28px',
  },
  updateTitle: {
    color: '#111827',
    fontSize: '14px',
    fontWeight: 700,
    lineHeight: '22px',
    margin: '0 0 4px',
  },
  footer: {
    textAlign: 'center',
  },
  footerText: {
    color: '#6b7280',
    fontSize: '12px',
    lineHeight: '20px',
    margin: '0 0 8px',
  },
  footerLink: {
    color: '#6d28d9',
    textDecoration: 'underline',
  },
} as const;

// benchmarks/cross-library/mjml-react/template.tsx
/** @jsxRuntime automatic */
/** @jsxImportSource react */

import {
  Mjml,
  MjmlBody,
  MjmlButton,
  MjmlColumn,
  MjmlDivider,
  MjmlFont,
  MjmlHead,
  MjmlImage,
  MjmlPreview,
  MjmlSection,
  MjmlText,
  MjmlWrapper,
} from '@faire/mjml-react';
import type { ReactElement, ReactNode } from 'react';
import {
  features,
  footerLinks,
  marketingProps,
  products,
  updates,
} from '../shared/fixture-data';

export type MjmlMarketingEmailProps = {
  preview?: string;
  headline?: ReactNode;
  intro?: ReactNode;
  ctaHref?: string;
  footerReason?: ReactNode;
};

export function MjmlMarketingEmail(
  props: MjmlMarketingEmailProps = {},
): ReactElement {
  const data = { ...marketingProps, ...props };
  return (
    <Mjml>
      <MjmlHead>
        <MjmlFont
          name="system"
          href="https://fonts.googleapis.com/css2?family=Inter:wght@400;700&display=swap"
        />
        <MjmlPreview>{data.preview}</MjmlPreview>
      </MjmlHead>
      <MjmlBody backgroundColor="#f6f9fc" width={640}>
        {/* Container */}
        <MjmlWrapper
          backgroundColor="#ffffff"
          border="1px solid #e5e7eb"
          borderRadius="16px"
          padding="32px"
        >
          {/* Hero */}
          <MjmlSection
            backgroundColor="#111827"
            borderRadius="14px"
            padding="32px"
          >
            <MjmlColumn>
              <MjmlText
                fontSize="32px"
                lineHeight="40px"
                color="#ffffff"
                fontWeight="700"
                margin="0 0 16px"
              >
                {data.headline}
              </MjmlText>
              <MjmlText
                fontSize="16px"
                lineHeight="26px"
                color="#d1d5db"
                margin="0 0 24px"
              >
                {data.intro}
              </MjmlText>
              <MjmlButton
                backgroundColor="#7c3aed"
                borderRadius="8px"
                color="#ffffff"
                fontSize="15px"
                fontWeight="700"
                padding="14px 22px"
                href={data.ctaHref}
              >
                View the launch notes
              </MjmlButton>
            </MjmlColumn>
          </MjmlSection>

          <MjmlDivider borderColor="#e5e7eb" padding="28px 0" />

          {/* Features */}
          <MjmlSection>
            <MjmlColumn>
              <MjmlText
                fontSize="22px"
                lineHeight="30px"
                color="#111827"
                fontWeight="700"
                margin="0 0 16px"
              >
                What this fixture covers
              </MjmlText>
              {features.map((feature) => (
                <MjmlSection
                  key={feature.title}
                  backgroundColor="#f9fafb"
                  border="1px solid #e5e7eb"
                  borderRadius="12px"
                  padding="16px"
                >
                  <MjmlColumn>
                    <MjmlText
                      fontSize="16px"
                      lineHeight="24px"
                      color="#111827"
                      fontWeight="700"
                      margin="0 0 6px"
                    >
                      {feature.title}
                    </MjmlText>
                    <MjmlText
                      fontSize="14px"
                      lineHeight="22px"
                      color="#4b5563"
                      margin="0"
                    >
                      {feature.body}
                    </MjmlText>
                  </MjmlColumn>
                </MjmlSection>
              ))}
            </MjmlColumn>
          </MjmlSection>

          {/* Products */}
          <MjmlSection padding="8px 0">
            <MjmlColumn>
              <MjmlText
                fontSize="22px"
                lineHeight="30px"
                color="#111827"
                fontWeight="700"
                margin="0 0 16px"
              >
                Product highlights
              </MjmlText>
            </MjmlColumn>
          </MjmlSection>
          <MjmlSection>
            {products.map((product) => (
              <MjmlColumn key={product.title} padding="12px">
                <MjmlImage
                  width="72px"
                  height="72px"
                  src={product.image}
                  alt={`${product.title} icon`}
                  borderRadius="14px"
                  padding="0 0 10px"
                />
                <MjmlText
                  fontSize="14px"
                  lineHeight="20px"
                  color="#111827"
                  fontWeight="700"
                  align="center"
                  margin="0"
                >
                  {product.title}
                </MjmlText>
                <MjmlText
                  fontSize="13px"
                  lineHeight="18px"
                  color="#7c3aed"
                  fontWeight="700"
                  align="center"
                  margin="4px 0 0"
                >
                  {product.price}
                </MjmlText>
              </MjmlColumn>
            ))}
          </MjmlSection>

          {/* Release notes */}
          <MjmlSection>
            <MjmlColumn>
              <MjmlText
                fontSize="22px"
                lineHeight="30px"
                color="#111827"
                fontWeight="700"
                margin="0 0 16px"
              >
                Release notes
              </MjmlText>
            </MjmlColumn>
          </MjmlSection>
          {updates.map((update) => (
            <MjmlSection key={update.title}>
              <MjmlColumn width="44px">
                <MjmlText
                  fontSize="12px"
                  lineHeight="28px"
                  color="#6d28d9"
                  fontWeight="700"
                  backgroundColor="#ede9fe"
                  borderRadius="999px"
                  align="center"
                  margin="0"
                >
                  {update.title.split(' ')[2]}
                </MjmlText>
              </MjmlColumn>
              <MjmlColumn>
                <MjmlText
                  fontSize="14px"
                  lineHeight="22px"
                  color="#111827"
                  fontWeight="700"
                  margin="0 0 4px"
                >
                  {update.title}
                </MjmlText>
                <MjmlText
                  fontSize="14px"
                  lineHeight="22px"
                  color="#4b5563"
                  margin="0 0 12px"
                >
                  {update.body}
                </MjmlText>
              </MjmlColumn>
            </MjmlSection>
          ))}

          <MjmlDivider borderColor="#e5e7eb" padding="28px 0" />

          {/* Footer */}
          <MjmlSection>
            <MjmlColumn>
              <MjmlText
                fontSize="12px"
                lineHeight="20px"
                color="#6b7280"
                align="center"
                margin="0 0 8px"
              >
                {data.footerReason}
              </MjmlText>
              <MjmlText
                fontSize="12px"
                lineHeight="20px"
                color="#6b7280"
                align="center"
                margin="0"
              >
                {footerLinks.map(([label, href], index) => (
                  <span key={href}>
                    {index > 0 ? ' · ' : ''}
                    <a href={href} style={{ color: '#6d28d9' }}>
                      {label}
                    </a>
                  </span>
                ))}
              </MjmlText>
            </MjmlColumn>
          </MjmlSection>
        </MjmlWrapper>
      </MjmlBody>
    </Mjml>
  );
}

export const createMjmlMarketingEmail = (props?: MjmlMarketingEmailProps) => (
  <MjmlMarketingEmail {...props} />
);
